pipeline:
  name: pl_auto_gitx_2nnmF
  identifier: pl_auto_gitx_2nnmF
  projectIdentifier: AmitTest
  orgIdentifier: GitXOrg
  tags: {}
  stages:
    - stage:
        name: stage1
        identifier: stage1
        template:
          templateRef: account.demoStage
          versionLabel: v1
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: q1
                      type: HarnessApproval
                      spec:
                        approvers:
                          userGroups: <+input>
