inputSet:
  identifier: prodInputSet
  name: prodInputSet
  orgIdentifier: Simlified_Git_sync
  projectIdentifier: SimplifiedGitSync_Do_Not_Delete
  pipeline:
    identifier: importApiAutomationPipeline
    stages:
    - stage:
        identifier: "A3"
        type: "Approval"
        spec:
          execution:
            steps:
            - step:
                identifier: "A4"
                type: "HarnessApproval"
                spec:
                  approvers:
                    userGroups:
                    - "account.viewer"
